### AutoLogin PyHouse ###
###
### This is appended (once) to ~/.bashrc
#
# Start the pyhouse process if we autologin this user
#
if [ $(tty) == /dev/tty1 ]; then
        bin/start_pyhouse
fi
### END DBK
